In [1]:
# for decimal division
from __future__ import division
import sys

import cvxopt
import numpy as np
from pylab import *
import math

from cvxpy import *

In [2]:
# Taken from CVX website http://cvxr.com/cvx/examples/
# Derived from Example: Finding the fastest mixing Markov chain on a graph
# Ported from cvx matlab to cvxpy by Misrab Faizullah-Khan
# Original comments below

# Boyd & Vandenberghe, "Convex Optimization"
# Joelle Skaf - 08/23/05
#
# Solved a QCQP with 3 inequalities:
#           minimize    1/2 x'*P0*x + q0'*r + r0
#               s.t.    1/2 x'*Pi*x + qi'*r + ri <= 0   for i=1,2,3
# and verifies that strong duality holds.

In [3]:
# Input data
n = 6
eps = sys.float_info.epsilon

P0 = cvxopt.normal(n, n)
eye = cvxopt.spmatrix(1.0, range(n), range(n))
P0 = P0.T * P0 + eps * eye

print P0

[ 3.57e+00 -1.66e-01 -1.19e+00  4.23e+00 -1.21e+00 -8.15e-01]
[-1.66e-01  9.20e-01  1.27e+00  4.19e-01 -1.81e-01  2.28e-01]
[-1.19e+00  1.27e+00  5.97e+00 -3.59e+00 -5.72e-01  6.99e-01]
[ 4.23e+00  4.19e-01 -3.59e+00  1.32e+01  8.04e-01 -5.37e-01]
[-1.21e+00 -1.81e-01 -5.72e-01  8.04e-01  1.77e+00  1.74e+00]
[-8.15e-01  2.28e-01  6.99e-01 -5.37e-01  1.74e+00  4.57e+00]



In [6]:
P1 = cvxopt.normal(n, n)
P1 = P1.T*P1
P2 = cvxopt.normal(n, n)
P2 = P2.T*P2
P3 = cvxopt.normal(n, n)
P3 = P3.T*P3

q0 = cvxopt.normal(n, 1)
q1 = cvxopt.normal(n, 1)
q2 = cvxopt.normal(n, 1)
q3 = cvxopt.normal(n, 1)

r0 = cvxopt.normal(1, 1)
r1 = cvxopt.normal(1, 1)
r2 = cvxopt.normal(1, 1)
r3 = cvxopt.normal(1, 1)

In [10]:
# Form the problem
x = Variable(n)
objective = Minimize(0.5*quad_form(x,P0) + q0.T*x)
#objective = Minimize( 0.5*quad_form(x,P0) + q0.T*x + r0 )
constraints = [ 0.5*quad_form(x,P1) + q1.T*x + r1 <= 0,
                0.5*quad_form(x,P2) + q2.T*x + r2 <= 0,
                0.5*quad_form(x,P3) + q3.T*x + r3 <= 0
               ]

TypeError: <type 'cvxopt.base.matrix'> is not a valid type for a Constant value.

In [11]:
import cvxpy as cvx
import numpy as np

# Make random input repeatable. 
np.random.seed(0) 

# Matrix size parameters.
n = 20
m = 10
p = 5

# Generate random problem data.
tmp = np.mat(np.random.rand(n, 1))
A = np.mat(np.random.randn(m, n))
b = A*tmp
F = np.mat(np.random.randn(p, n))
g = F*tmp + np.mat(np.random.rand(p, 1))

In [12]:
# Entropy maximization.
x = cvx.Variable(n)
obj = cvx.Maximize(cvx.sum_entries(cvx.entr(x)))
constraints = [A*x == b,
               F*x <= g ]
prob = cvx.Problem(obj, constraints)
prob.solve(solver=cvx.CVXOPT, verbose=True)

# Print result.
print "\nThe optimal value is:", prob.value
print '\nThe optimal solution is:'
print x.value

     pcost       dcost       gap    pres   dres
 0:  0.0000e+00 -7.5220e+00  2e+01  1e+00  1e+00
 1: -6.0720e+00 -5.9875e+00  2e+00  1e-01  2e-01
 2: -5.4688e+00 -5.5885e+00  4e-01  2e-02  5e-02
 3: -5.4595e+00 -5.4889e+00  5e-02  2e-03  2e-02
 4: -5.4763e+00 -5.4816e+00  1e-02  3e-04  7e-03
 5: -5.4804e+00 -5.4809e+00  1e-03  4e-05  2e-03
 6: -5.4809e+00 -5.4809e+00  3e-05  1e-06  4e-04
 7: -5.4809e+00 -5.4809e+00  4e-07  1e-08  2e-05
 8: -5.4809e+00 -5.4809e+00  4e-09  1e-10  3e-07
 9: -5.4809e+00 -5.4809e+00  4e-11  1e-12  5e-09
Optimal solution found.

The optimal value is: 5.48090148635

The optimal solution is:
[[ 0.43483319]
 [ 0.66111715]
 [ 0.49201039]
 [ 0.36030618]
 [ 0.38416629]
 [ 0.30283658]
 [ 0.41730232]
 [ 0.79107794]
 [ 0.76667302]
 [ 0.38292365]
 [ 1.2479328 ]
 [ 0.50416987]
 [ 0.68053832]
 [ 0.67163958]
 [ 0.13877259]
 [ 0.5248668 ]
 [ 0.08418897]
 [ 0.56927148]
 [ 0.50000248]
 [ 0.78291311]]


## QCQP

In [ ]:
cvx.QCQP()

In [18]:
def dec_to_bin(number):
    
    if number < 2:
        
        return str(number)
    
    else:
        
        return dec_to_bin((input/2)) + str(input%2)

In [19]:
dec_to_bin(6)

TypeError: unsupported operand type(s) for /: 'function' and 'int'

In [14]:
test = [1,5,3,6,8,4,8,2,5,7]

In [15]:
bubble_sort(test)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 8]

In [20]:
1 and 2 < 3

True

In [21]:
a = None
b = None
c = None

In [22]:
a and b == c

In [23]:
gin = [[1,10], [5,8], [8,15]]

In [30]:
max(max(gin))

15

In [31]:
min(min(gin))

1

In [36]:
test = [[1, 0, 1], [1, 0, 1], [1, 0, 1]]

In [37]:
[list(item) for item in zip(*test)]

[[1, 1, 1], [0, 0, 0], [1, 1, 1]]